baseURL: "https://localhost/"
defaultContentLanguage: "zh-cn"

timeout: 150s
publishDir: "public"
metaDataFormat: "yaml"
SectionPagesMenu: "sectionMenus"

disableKinds: []
# log level (debug|info|warn|error)
logLevel: "error"

paginate: 2
paginatepath: page

# https://gohugo.io/getting-started/configuration/#configure-title-case
# (ap|chicago|go|firstupper|none)
# ap 使用美联社样本中发布的大小写规则。
# chicago 使用《芝加哥风格手册》中发布的大小写规则。
# go 每个单词的第一个字母大写。
# firstupper 将第一个单词的第一个字母大写。
# none 禁用自动节标题的转换，并禁用 strings.Title 函数执行的转换。如果您希望根据需要手动大写章节标题，并绕过 strings.Title 函数的固执己见的主题使用，这非常有用。
titleCaseStyle: none

#watch: true
#debug: true
minify: true
#uglyURLs: true
#multihost: false
buildDrafts: true
buildFuture: true
enableEmoji: true
buildExpired: false
enableGitInfo: true
enableRobotsTXT: true
printMemoryUsage: true
printPathWarnings: true
printI18nWarnings: true
cleanDestinationDir: true
pluralizeListTitles: true
printUnusedTemplates: true
enableInlineShortcodes: true
disableHugoGeneratorInject: false
defaultContentLanguageInSubDir: true
enableMissingTranslationPlaceholders: false
