baseURL: "https://localhost/"

timeout: 150s
publishDir: "public"
metaDataFormat: "yaml"
SectionPagesMenu: "sectionMenus"
defaultContentLanguage: "zh-cn"

disableKinds: []
# log level (debug|info|warn|error)
logLevel: "error"

paginate: 2
paginatepath: page

#titleCaseStyle: none

#watch: true
#debug: true
minify: true
#uglyURLs: true
#multihost: false
buildDrafts: true
buildFuture: true
enableEmoji: true
buildExpired: false
enableGitInfo: true
enableRobotsTXT: true
printMemoryUsage: true
printPathWarnings: true
printI18nWarnings: true
cleanDestinationDir: true
pluralizeListTitles: false
printUnusedTemplates: true
enableInlineShortcodes: true
#disableHugoGeneratorInject: true
defaultContentLanguageInSubDir: true
enableMissingTranslationPlaceholders: false
