baseURL: "http://localhost/"

metaDataFormat: "yaml"
disableKinds: [ "taxonomy", "term" ]

logFile: "hugo_log/hugo_log.default.log"

publishDir: "public"

defaultContentLanguage: "zh-cn"

languages:
    zh-cn:
        # baseURL: ""
        languageName: "中文（简体）"
        languageDirection: "ltr"
        languageCode: "zh-CN"
        timeZone: "Asia/Shanghai"
        title: "杰格网"
        weight: 1
        params:
            icon: cn
            Subtitle: "子标题"
            Description: "默认描述"

    en-us:
        # baseURL: ""
        languageName: "English"
        languageDirection: "ltr"
        languageCode: "en-US"
        timeZone: "America/New_York"
        title: "JieGe"
        weight: 6
        params:
            icon: us
            Subtitle: "Subtitle"
            Description: "Default Description"

menu:
    main:
        -   identifier: menu_home
            pageRef: /
            weight: 1
        -   identifier: menu_demo
            pageRef: /demo
            weight: 4
        -   identifier: demo_login
            pageRef: /demo/login
            parent: menu_demo
            weight: 1
        -   identifier: demo_signup
            pageRef: /demo/signup
            parent: menu_demo
            weight: 2
        -   identifier: demo_reset
            pageRef: /demo/reset
            parent: menu_demo
            weight: 3
        -   identifier: demo_change
            pageRef: /demo/change
            parent: menu_demo
            weight: 4
        -   identifier: demo_find
            pageRef: /demo/find
            parent: menu_demo
            weight: 5
        -   identifier: demo_logout
            pageRef: /demo/logout
            parent: menu_demo
            weight: 6
        -   identifier: menu_more
            pageRef:
            weight: 7
        -   identifier: menu_contact
            pageRef: /contact
            parent: menu_more
            weight: 1
        -   identifier: menu_about
            pageRef: /about
            parent: menu_more
            weight: 2
        -   identifier: menu_ad
            pageRef: /ad
            parent: menu_more
            weight: 3
        -   identifier: menu_chatgpt
            pageRef: /chatgpt
            parent: menu_more
            weight: 4
        -   identifier: demo_login_normal
            pageRef: /demo/login/normal
            parent: demo_login
            weight: 1
        -   identifier: demo_login_email
            pageRef: /demo/login/email
            parent: demo_login
            weight: 2
        -   identifier: demo_login_sms
            pageRef: /demo/login/sms
            parent: demo_login
            weight: 3
        -   identifier: demo_signup_normal
            pageRef: /demo/signup/normal
            parent: demo_signup
            weight: 1
        -   identifier: demo_signup_email
            pageRef: /demo/signup/email
            parent: demo_signup
            weight: 2
        -   identifier: demo_signup_sms
            pageRef: /demo/signup/sms
            parent: demo_signup
            weight: 3
        -   identifier: demo_reset_email
            pageRef: /demo/reset/email
            parent: demo_reset
            weight: 1
        -   identifier: demo_reset_sms
            pageRef: /demo/reset/sms
            parent: demo_reset
            weight: 2
        -   identifier: demo_change_password
            pageRef: /demo/change/password
            parent: demo_change
            weight: 1
        -   identifier: demo_change_email
            pageRef: /demo/change/email
            parent: demo_change
            weight: 2
        -   identifier: demo_change_phone
            pageRef: /demo/change/phone
            parent: demo_change
            weight: 3
        -   identifier: demo_find_email
            pageRef: /demo/find/email
            parent: demo_find
            weight: 1
        -   identifier: demo_find_sms
            pageRef: /demo/find/sms
            parent: demo_find
            weight: 2
        -   identifier: demo_logout_normal
            pageRef: /demo/logout/normal
            parent: demo_logout
            weight: 1
    theme:
        -   identifier: theme_light
            weight: 1
            params:
                svg: "sun-fill"
                theme_value: "light"
        -   identifier: theme_dark
            weight: 2
            params:
                svg: "moon-stars-fill"
                theme_value: "dark"
        -   identifier: theme_auto
            weight: 3
            params:
                svg: "circle-half"
                theme_value: "auto"

#watch: true
#debug: true
#minify: true
#uglyURLs: true
#multihost: false
buildDrafts: true
buildFuture: true
enableEmoji: true
buildExpired: false
enableGitInfo: true
hasCJKLanguage: true
enableRobotsTXT: true
printI18nWarnings: true
cleanDestinationDir: true
printUnusedTemplates: true
enableInlineShortcodes: true
#disableHugoGeneratorInject: true
defaultContentLanguageInSubDir: true
enableMissingTranslationPlaceholders: true

FrontMatter:
    date:
        - date
        - publishDate
        - lastmod
    expiryDate:
        - expiryDate
    lastMod:
        - :git
        - lastmod
        - date
        - publishDate
    publishDate:
        - date
        - publishDate

markup:
    goldmark:
        renderer:
            unsafe: true
    tableOfContents:
        startLevel: 2
        endLevel: 4

security:
    enableInlineShortcodes: false
    funcs:
        getenv:
            - ^HUGO_
            - ^CI$

#server:
#    -   redirects:
#            from: /zh-cn/**
#            to: /zh-cn/404.html
#            status: 404
#    -   redirects:
#            from: /en-us/**
#            to: /en-us/404.html
#            status: 404

outputFormats:
    RSS:
        baseName: rss

sitemap:
    ChangeFreq: monthly
    filename: sitemap.xml
    priority: 0.5

module:
    hugoVersion:
        extended: true
        max: "0.111.3"
        min: "0.108.0"
    mounts:
        -   source: site/archetypes
            target: archetypes

        -   source: site/static
            target: static/static
            excludeFiles: "{CNAME}"
        -   source: site/static/CNAME
            target: static/CNAME
        -   source: node_modules
            target: static/static/vendor
            includeFiles: "{bootstrap,js-cookie,localforage,lozad,@docsearch,b-components-js,qrcode,xgplayer,danmu.js,headroom.js,fullpage.js,lax.js,parallax-controller,clipboard,html2canvas,@fortawesome,flag-icons,randomColor}/**"

        -   source: site/content
            target: content
            lang: zh-cn
        -   source: site/content
            target: content
            lang: en-us

        -   source: site/assets
            target: static/assets

        -   source: site/data
            target: data
        -   source: site/i18n
            target: i18n
        -   source: site/layouts
            target: layouts

Params:
    icp: "冀ICP备12018851号-7"
    beian: "9999999999999999"

    demo_version: "5.3"
    bootstrap_version: "5.3.0-alpha3"

    since: "2020"

    CopyleftText: "Company, Inc. All rights reserved."
    CopyrightText: "Company, Inc. All rights reserved."

    Repo:
        git: "https://github.com/jzeg-net/jzeg-net.github.io"
        # 可选[blame,blob,raw,edit]
        AccessType: "edit"

    qrcode:
        alipay:
            donate: HTTPS://QR.ALIPAY.COM/FKX15775Y9K2OJJELTYUQ20
            account:
            group:
        weixin:
            donate: wxp://f2f0H7xW3hJst1JoX3lEdTm8ZYjfkZPKQo5XSe57dnbv11g=
            account:
            group:
        qq:
            donate: https://i.qianbao.qq.com/wallet/sqrcode.htm?m=tenpay&f=wallet&a=1&ac=CAEQguvBjgUYz9KShwY%3D_xxx_sign&u=1372616066&n=%E8%A7%A3%E6%9E%90%E7%9F%AD%E8%A7%86%E9%A2%91
            account:
            group:
