baseURL: "https://localhost/"

metaDataFormat: "yaml"
disableKinds: [ "taxonomy", "term" ]

# log level (debug|info|warn|error)
logLevel: "error"

publishDir: "public"

timeout: 70s
defaultContentLanguage: "zh-cn"

languages:
    zh-cn:
        # baseURL: ""
        languageName: "中文（简体）"
        languageDirection: "ltr"
        languageCode: "zh-CN"
        timeZone: "Asia/Shanghai"
        title: "杰格网"
        weight: 1
        hasCJKLanguage: true
        params:
            icon: cn
            Subtitle: "子标题"
            Description: "默认描述"
            header_separator: " - "

    en-us:
        # baseURL: ""
        languageName: "English"
        languageDirection: "ltr"
        languageCode: "en-US"
        timeZone: "America/New_York"
        title: "JieGe"
        weight: 6
        hasCJKLanguage: false
        params:
            icon: us
            Subtitle: "Subtitle"
            Description: "Default Description"
            header_separator: " - "

menu:
    main:
        -   identifier: menu_home
            pageRef: /
            weight: 1
            params:
                class:
                svg:
                    useHref:
                    class:
                    size: [ width: 16, height: 16 ]
        -   identifier: menu_posts
            pageRef: /posts
            weight: 2
            params:
                class:
                svg:
                    useHref:
                    class:
                    size: [ width: 16, height: 16 ]
        -   identifier: menu_gallery
            pageRef: /gallery
            weight: 3
            params:
                class:
                svg:
                    useHref:
                    class:
                    size: [ width: 16, height: 16 ]
        -   identifier: menu_video
            pageRef: /video
            weight: 3
            params:
                class:
                svg:
                    useHref:
                    class:
                    size: [ width: 16, height: 16 ]
        -   identifier: menu_more
            pageRef:
            weight: 7
            params:
                class:
                svg:
                    useHref:
                    class:
                    size: [ width: 16, height: 16 ]
        -   identifier: menu_contact
            pageRef: /contact
            parent: menu_more
            weight: 1
            params:
                class:
                svg:
                    useHref:
                    class:
                    size: [ width: 16, height: 16 ]
        -   identifier: menu_about
            pageRef: /about
            parent: menu_more
            weight: 2
            params:
                class:
                svg:
                    useHref:
                    class:
                    size: [ width: 16, height: 16 ]
        -   identifier: menu_ad
            pageRef: /ad
            parent: menu_more
            weight: 3
            params:
                class:
                svg:
                    useHref:
                    class:
                    size: [ width: 16, height: 16 ]
        -   identifier: menu_chatgpt
            pageRef: /chatgpt
            parent: menu_more
            weight: 4
            params:
                class:
                svg:
                    useHref:
                    class:
                    size: [ width: 16, height: 16 ]
        -   identifier: menu_tools
            pageRef: /tools
            parent: menu_more
            weight: 5
            params:
                class:
                svg:
                    useHref:
                    class:
                    size: [ width: 16, height: 16 ]
        -   identifier: menu_edit
            pageRef: /edit
            parent: menu_more
            weight: 8
            params:
                class:
                svg:
                    useHref:
                    class:
                    size: [ width: 16, height: 16 ]
    demo:
        -   identifier: menu_demo
            pageRef: /demo
            weight: 1
            params:
                class:
                svg:
                    useHref:
                    class:
                    size: [ width: 16, height: 16 ]
        -   identifier: demo_login
            pageRef: /demo/login
            parent: menu_demo
            weight: 1
        -   identifier: demo_signup
            pageRef: /demo/signup
            parent: menu_demo
            weight: 2
        -   identifier: demo_reset
            pageRef: /demo/reset
            parent: menu_demo
            weight: 3
        -   identifier: demo_change
            pageRef: /demo/change
            parent: menu_demo
            weight: 4
        -   identifier: demo_find
            pageRef: /demo/find
            parent: menu_demo
            weight: 5
        -   identifier: demo_logout
            pageRef: /demo/logout
            parent: menu_demo
            weight: 6
        -   identifier: demo_login_normal
            pageRef: /demo/login/normal
            parent: demo_login
            weight: 1
        -   identifier: demo_login_email
            pageRef: /demo/login/email
            parent: demo_login
            weight: 2
        -   identifier: demo_login_sms
            pageRef: /demo/login/sms
            parent: demo_login
            weight: 3
        -   identifier: demo_signup_normal
            pageRef: /demo/signup/normal
            parent: demo_signup
            weight: 1
        -   identifier: demo_signup_email
            pageRef: /demo/signup/email
            parent: demo_signup
            weight: 2
        -   identifier: demo_signup_sms
            pageRef: /demo/signup/sms
            parent: demo_signup
            weight: 3
        -   identifier: demo_reset_email
            pageRef: /demo/reset/email
            parent: demo_reset
            weight: 1
        -   identifier: demo_reset_sms
            pageRef: /demo/reset/sms
            parent: demo_reset
            weight: 2
        -   identifier: demo_change_password
            pageRef: /demo/change/password
            parent: demo_change
            weight: 1
        -   identifier: demo_change_email
            pageRef: /demo/change/email
            parent: demo_change
            weight: 2
        -   identifier: demo_change_phone
            pageRef: /demo/change/phone
            parent: demo_change
            weight: 3
        -   identifier: demo_find_email
            pageRef: /demo/find/email
            parent: demo_find
            weight: 1
        -   identifier: demo_find_sms
            pageRef: /demo/find/sms
            parent: demo_find
            weight: 2
        -   identifier: demo_logout_normal
            pageRef: /demo/logout/normal
            parent: demo_logout
            weight: 1
    knowledge_labor_union:
        -   identifier: zhgh_page
            pageRef: /tools/zhgh
            weight: 1
        -   identifier: zhgh_study
            pageRef: /tools/zhgh/study
            parent: zhgh_page
            weight: 1
        -   identifier: zhgh_passwork
            pageRef: /tools/zhgh/passwork
            parent: zhgh_page
            weight: 2
        -   identifier: zhgh_member
            pageRef: /tools/zhgh/member
            parent: zhgh_page
            weight: 3
        -   identifier: zhgh_login
            pageRef: /tools/zhgh/login
            parent: zhgh_page
            weight: 4
        -   identifier: zhgh_data
            pageRef: /tools/zhgh/data
            parent: zhgh_page
            weight: 9
        -   identifier: zhgh_log
            pageRef: /tools/zhgh/log
            parent: zhgh_page
            weight: 10
    donate:
        -   identifier: donate_alipay
            weight: 1
            params:
                donate_value: "alipay"
                class:
                svg:
                    useHref: "bi-alipay"
                    class: "bi fs-5 text-primary"
        -   identifier: donate_wechat
            weight: 2
            params:
                donate_value: "wechat"
                class:
                svg:
                    useHref: "bi-wechat"
                    class: "bi fs-5 text-success"
    theme:
        -   identifier: theme_dark
            weight: 1
            params:
                theme_value: "dark"
                class:
                svg:
                    useHref: "bi-moon-stars"
                    class: "bi fs-5 me-2"
                    size: [ width: 16, height: 16 ]
        -   identifier: theme_light
            weight: 2
            params:
                theme_value: "light"
                class:
                svg:
                    useHref: "bi-sun"
                    class: "bi fs-5 me-2"
                    size: [ width: 16, height: 16 ]
        -   identifier: theme_auto
            weight: 3
            params:
                theme_value: "auto"
                class:
                svg:
                    useHref: "bi-circle-half"
                    class: "bi fs-5 me-2"
                    size: [ width: 16, height: 16 ]
    palette:
        -   identifier: palette_none
            weight: 1
            params:
                palette_value: "none"
                class: "text-secondary"
                svg:
                    useHref: "bi-palette"
                    class: "bi fs-5 me-2"
                    size: [ width: 16, height: 16 ]
        -   identifier: palette_red
            weight: 10
            params:
                palette_value: "red"
                class: "text-danger"
                svg:
                    useHref: "bi-droplet-half"
                    class: "bi fs-5 me-2"
                    size: [ width: 16, height: 16 ]
        -   identifier: palette_green
            weight: 20
            params:
                palette_value: "green"
                class: "text-success"
                svg:
                    useHref: "bi-droplet-half"
                    class: "bi fs-5 me-2"
                    size: [ width: 16, height: 16 ]
        -   identifier: palette_blue
            weight: 30
            params:
                palette_value: "blue"
                class: "text-primary"
                svg:
                    useHref: "bi-droplet-half"
                    class: "bi fs-5 me-2"
                    size: [ width: 16, height: 16 ]
    font_size:
        -   identifier: fontSize_xs
            weight: -4
            params:
                size_value: "xs"
                class:
                svg:
                    useHref: "bi-fonts"
                    class: "bi fs-5 me-2"
                    size: [ width: 16, height: 16 ]
        -   identifier: fontSize_sm
            weight: -3
            params:
                size_value: "sm"
                class:
                svg:
                    useHref: "bi-fonts"
                    class: "bi fs-5 me-2"
                    size: [ width: 16, height: 16 ]
        -   identifier: fontSize_md
            weight: -2
            params:
                size_value: "md"
                class:
                svg:
                    useHref: "bi-fonts"
                    class: "bi fs-5 me-2"
                    size: [ width: 16, height: 16 ]
        -   identifier: fontSize_base
            weight: -1
            params:
                size_value: "base"
                class:
                svg:
                    useHref: "bi-fonts"
                    class: "bi fs-5 me-2"
                    size: [ width: 16, height: 16 ]
        -   identifier: fontSize_lg
            weight: 1
            params:
                size_value: "lg"
                class:
                svg:
                    useHref: "bi-fonts"
                    class: "bi fs-5 me-2"
                    size: [ width: 16, height: 16 ]
        -   identifier: fontSize_xl
            weight: 2
            params:
                size_value: "xl"
                class:
                svg:
                    useHref: "bi-fonts"
                    class: "bi fs-5 me-2"
                    size: [ width: 16, height: 16 ]
        -   identifier: fontSize_2xl
            weight: 3
            params:
                size_value: "2xl"
                class:
                svg:
                    useHref: "bi-fonts"
                    class: "bi fs-5 me-2"
                    size: [ width: 16, height: 16 ]

#watch: true
#debug: true
minify: true
#uglyURLs: true
#multihost: false
buildDrafts: true
buildFuture: true
enableEmoji: true
buildExpired: false
enableGitInfo: true
enableRobotsTXT: true
printMemoryUsage: true
printPathWarnings: true
printI18nWarnings: true
cleanDestinationDir: true
printUnusedTemplates: true
enableInlineShortcodes: true
#disableHugoGeneratorInject: true
defaultContentLanguageInSubDir: true
enableMissingTranslationPlaceholders: true

paginate: 2
paginatepath: page

#minify:
#    minifyOutput: true
#    tdewolff:
#        html:
#            keepQuotes: true

FrontMatter:
    date:
        - date
        - publishDate
        - lastmod
    expiryDate:
        - expiryDate
    lastMod:
        - :git
        - lastmod
        - date
        - publishDate
    publishDate:
        - date
        - publishDate

markup:
    goldmark:
        renderer:
            unsafe: true
    tableOfContents:
        startLevel: 2
        endLevel: 5

security:
    enableInlineShortcodes: false
    funcs:
        getenv: [ '^HUGO_', '^CI$' ]
    exec:
        allow: [ '^npx$', '^babel$' ]

#server:
#    -   redirects:
#            from: /zh-cn/**
#            to: /zh-cn/404.html
#            status: 404
#    -   redirects:
#            from: /en-us/**
#            to: /en-us/404.html
#            status: 404

outputFormats:
    RSS:
        baseName: rss

sitemap:
    ChangeFreq: monthly
    filename: sitemap.xml
    priority: 0.5

module:
    hugoVersion:
        extended: true
        max: "0.118.2"
        min: "0.118.2"
    mounts:
        -   source: site/archetypes
            target: archetypes

        -   source: site/static
            target: static/static
            excludeFiles: "{CNAME}"
        -   source: site/static/CNAME
            target: static/CNAME
        -   source: node_modules
            target: static/static/vendor
            includeFiles: "{bootstrap,bootstrap-icons,js-cookie,github-api,workbox-sw,wretch,localforage,dayjs,timeago.js,lozad,@docsearch,b-components-js,qrcode,vditor,simple-datatables,@glidejs,xgplayer,danmu.js,lax.js,parallax-controller,clipboard,html2canvas,flag-icons,randomColor}/**"

        -   source: site/content
            target: content
            lang: zh-cn
        -   source: site/content
            target: content
            lang: en-us

        -   source: site/assets
            target: assets

        -   source: site/data
            target: data
        -   source: site/i18n
            target: i18n
        -   source: site/layouts
            target: layouts

Params:
    # default theme mode
    theme:
        enable: true
        default: light
        option: [ 'light',"dark","auto" ]

    # default palette color
    palette:
        enable: true
        default: none
        option: [ "none","blue","green","orange","red","yellow" ]

    # default font size
    font:
        enable: false
        # default size
        size:
            enable: true
            default: base
            option: [ "xs","sm","md","base","lg","xl","2xl","3xl","4xl","5xl","6xl","7xl","8xl","9xl" ]

    post:
        sidebar:
            enable: true
            # Sidebar Type [ collapse | offcanvas ]
            type: collapse

    float_tools:
        enable: true

    breadcrumb:
        enable: true

    search:
        enable: true
        # type of search engine ["lunr", "algolia", "fuse"]
        type: "lunr"
        algolia:
            index:
            appID:
            searchKey:
        fuse:
            # https://fusejs.io/api/options.html
            isCaseSensitive: false
            minMatchCharLength: 2
            findAllMatches: false
            location: 0
            threshold: 0.3
            distance: 100
            ignoreLocation: false
            useExtendedSearch: false
            ignoreFieldNorm: false

    icp: "冀ICP备12018851号-7"
    beian: "9999999999999999"

    demo_version: "5.3"
    bootstrap_version: "5.3.0"

    since: "2020"

    CopyleftText: "Company, Inc. All rights reserved."
    CopyrightText: "Company, Inc. All rights reserved."

    Github:
        root: "https://github.com/"
        organizations: ""
        username: ""
        repository: ""

    Repo:
        git: "https://github.com/jzeg-net/jzeg-net.github.io"

    qrcode:
        alipay:
            donate: HTTPS://QR.ALIPAY.COM/FKX15775Y9K2OJJELTYUQ20
            account:
            group:
        weixin:
            donate: wxp://f2f0H7xW3hJst1JoX3lEdTm8ZYjfkZPKQo5XSe57dnbv11g=
            account:
            group:
        qq:
            donate: https://i.qianbao.qq.com/wallet/sqrcode.htm?m=tenpay&f=wallet&a=1&ac=CAEQguvBjgUYz9KShwY%3D_xxx_sign&u=1372616066&n=%E8%A7%A3%E6%9E%90%E7%9F%AD%E8%A7%86%E9%A2%91
            account:
            group:

    analytics:
        enable: false
        googleTagManager:
            enable: true
            id:
