# baseURL: ""
languageName: "简体中文"
languageDirection: "ltr"
languageCode: "zh-CN"
timeZone: "Asia/Shanghai"
title: "杰格网"
weight: 1
hasCJKLanguage: true
params:
    LanguageIcon: cn
    Subtitle: "子标题"
    Description: "默认描述"
    header_separator: " - "
