# baseURL: ""
languageName: "English"
languageDirection: "ltr"
languageCode: "en-US"
timeZone: "America/New_York"
title: "JieGe"
weight: 6
hasCJKLanguage: false
params:
    LanguageIcon: us
    Subtitle: "Subtitle"
    Description: "Default Description"
    header_separator: " - "
