main:
    -   name: "首页"
        pageRef: /
        weight: 1
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   name: "文章"
        pageRef: /posts
        weight: 2
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   name: "画廊"
        pageRef: /gallery
        weight: 3
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   name: "视频"
        pageRef: /video
        weight: 3
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   name: "更多"
        pageRef:
        weight: 7
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   name: "联系"
        pageRef: /contact
        parent: menu_more
        weight: 1
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   name: "关于"
        pageRef: /about
        parent: menu_more
        weight: 2
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   name: "广告"
        pageRef: /ad
        parent: menu_more
        weight: 3
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   name: "Chat GPT"
        pageRef: /chatgpt
        parent: menu_more
        weight: 4
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   name: "工具箱"
        pageRef: /tools
        parent: menu_more
        weight: 5
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   name: "编辑"
        pageRef: /edit
        parent: menu_more
        weight: 8
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   name: "铺子"
        pageRef: /shop
        parent: menu_more
        weight: 7
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
demo:
    -   name: "演示"
        pageRef: /demo
        weight: 1
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   name: "登录"
        pageRef: /demo/login
        parent: menu_demo
        weight: 1
    -   name: "注册"
        pageRef: /demo/signup
        parent: menu_demo
        weight: 2
    -   name: "重置"
        pageRef: /demo/reset
        parent: menu_demo
        weight: 3
    -   name: "修改"
        pageRef: /demo/change
        parent: menu_demo
        weight: 4
    -   name: "找回"
        pageRef: /demo/find
        parent: menu_demo
        weight: 5
    -   name: "退出"
        pageRef: /demo/logout
        parent: menu_demo
        weight: 6
    -   name: "正常登录"
        pageRef: /demo/login/normal
        parent: demo_login
        weight: 1
    -   name: "邮箱登录"
        pageRef: /demo/login/email
        parent: demo_login
        weight: 2
    -   name: "短信登录"
        pageRef: /demo/login/sms
        parent: demo_login
        weight: 3
    -   name: "正常注册"
        pageRef: /demo/signup/normal
        parent: demo_signup
        weight: 1
    -   name: "邮箱注册"
        pageRef: /demo/signup/email
        parent: demo_signup
        weight: 2
    -   name: "短信注册"
        pageRef: /demo/signup/sms
        parent: demo_signup
        weight: 3
    -   name: "通过邮箱重置"
        pageRef: /demo/reset/email
        parent: demo_reset
        weight: 1
    -   name: "通过短信重置"
        pageRef: /demo/reset/sms
        parent: demo_reset
        weight: 2
    -   name: "修改密码"
        pageRef: /demo/change/password
        parent: demo_change
        weight: 1
    -   name: "修改邮箱"
        pageRef: /demo/change/email
        parent: demo_change
        weight: 2
    -   name: "修改手机号"
        pageRef: /demo/change/phone
        parent: demo_change
        weight: 3
    -   name: "通过邮箱找回"
        pageRef: /demo/find/email
        parent: demo_find
        weight: 1
    -   name: "通过短信找回"
        pageRef: /demo/find/sms
        parent: demo_find
        weight: 2
    -   name: "正常退出"
        pageRef: /demo/logout/normal
        parent: demo_logout
        weight: 1
knowledge_labor_union:
    -   name: "智慧"
        pageRef: /tools/zhgh
        weight: 1
    -   name: "学习"
        pageRef: /tools/zhgh/study
        parent: zhgh_page
        weight: 1
    -   name: "闯关"
        pageRef: /tools/zhgh/passwork
        parent: zhgh_page
        weight: 2
    -   name: "会员"
        pageRef: /tools/zhgh/member
        parent: zhgh_page
        weight: 3
    -   name: "登录"
        pageRef: /tools/zhgh/login
        parent: zhgh_page
        weight: 4
    -   name: "数据"
        pageRef: /tools/zhgh/data
        parent: zhgh_page
        weight: 9
    -   name: "日志"
        pageRef: /tools/zhgh/log
        parent: zhgh_page
        weight: 10
donate:
    -   name: "支付宝"
        weight: 1
        params:
            donate_value: "alipay"
            class:
            svg:
                useHref: "bi-alipay"
                class: "text-primary"
    -   name: "微信"
        weight: 2
        params:
            donate_value: "wechat"
            class:
            svg:
                useHref: "bi-wechat"
                class: "text-success"
theme:
    -   name: "黑暗"
        weight: 1
        params:
            theme_value: "dark"
            class:
            svg:
                useHref: "bi-moon-stars"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   name: "明亮"
        weight: 2
        params:
            theme_value: "light"
            class:
            svg:
                useHref: "bi-sun"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   name: "自动"
        weight: 3
        params:
            theme_value: "auto"
            class:
            svg:
                useHref: "bi-circle-half"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
palette:
    -   name: "默认"
        weight: 1
        params:
            palette_value: "none"
            class: "text-secondary"
            svg:
                useHref: "bi-palette"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   name: "红"
        weight: 10
        params:
            palette_value: "red"
            class: "text-danger"
            svg:
                useHref: "bi-droplet-half"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   name: "绿"
        weight: 20
        params:
            palette_value: "green"
            class: "text-success"
            svg:
                useHref: "bi-droplet-half"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   name: "蓝"
        weight: 30
        params:
            palette_value: "blue"
            class: "text-primary"
            svg:
                useHref: "bi-droplet-half"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
font_size:
    -   name: "3xs"
        weight: -4
        params:
            size_value: "3xs"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   name: "2xs"
        weight: -3
        params:
            size_value: "2xs"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   name: "xs"
        weight: -2
        params:
            size_value: "xs"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   name: "sm"
        weight: -1
        params:
            size_value: "sm"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   name: "md"
        weight: 1
        params:
            size_value: "md"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   name: "lg"
        weight: 2
        params:
            size_value: "lg"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   name: "xl"
        weight: 3
        params:
            size_value: "xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   name: "2xl"
        weight: 4
        params:
            size_value: "2xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   name: "3xl"
        weight: 5
        params:
            size_value: "3xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   name: "4xl"
        weight: 6
        params:
            size_value: "4xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   name: "5xl"
        weight: 7
        params:
            size_value: "5xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   name: "6xl"
        weight: 8
        params:
            size_value: "6xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   name: "7xl"
        weight: 9
        params:
            size_value: "7xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   name: "8xl"
        weight: 10
        params:
            size_value: "8xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   name: "9xl"
        weight: 11
        params:
            size_value: "9xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
