main:
    -   identifier: menu_home
        pageRef: /
        weight: 1
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_posts
        pageRef: /posts
        weight: 2
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_gallery
        pageRef: /gallery
        weight: 3
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_video
        pageRef: /video
        weight: 3
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_more
        pageRef:
        weight: 7
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_contact
        pageRef: /contact
        parent: menu_more
        weight: 1
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_about
        pageRef: /about
        parent: menu_more
        weight: 2
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_ad
        pageRef: /ad
        parent: menu_more
        weight: 3
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_chatgpt
        pageRef: /chatgpt
        parent: menu_more
        weight: 4
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_tools
        pageRef: /tools
        parent: menu_more
        weight: 5
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_edit
        pageRef: /edit
        parent: menu_more
        weight: 8
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_shop
        pageRef: /shop
        parent: menu_more
        weight: 7
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
demo:
    -   identifier: menu_demo
        pageRef: /demo
        weight: 1
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: demo_login
        pageRef: /demo/login
        parent: menu_demo
        weight: 1
    -   identifier: demo_signup
        pageRef: /demo/signup
        parent: menu_demo
        weight: 2
    -   identifier: demo_reset
        pageRef: /demo/reset
        parent: menu_demo
        weight: 3
    -   identifier: demo_change
        pageRef: /demo/change
        parent: menu_demo
        weight: 4
    -   identifier: demo_find
        pageRef: /demo/find
        parent: menu_demo
        weight: 5
    -   identifier: demo_logout
        pageRef: /demo/logout
        parent: menu_demo
        weight: 6
    -   identifier: demo_login_normal
        pageRef: /demo/login/normal
        parent: demo_login
        weight: 1
    -   identifier: demo_login_email
        pageRef: /demo/login/email
        parent: demo_login
        weight: 2
    -   identifier: demo_login_sms
        pageRef: /demo/login/sms
        parent: demo_login
        weight: 3
    -   identifier: demo_signup_normal
        pageRef: /demo/signup/normal
        parent: demo_signup
        weight: 1
    -   identifier: demo_signup_email
        pageRef: /demo/signup/email
        parent: demo_signup
        weight: 2
    -   identifier: demo_signup_sms
        pageRef: /demo/signup/sms
        parent: demo_signup
        weight: 3
    -   identifier: demo_reset_email
        pageRef: /demo/reset/email
        parent: demo_reset
        weight: 1
    -   identifier: demo_reset_sms
        pageRef: /demo/reset/sms
        parent: demo_reset
        weight: 2
    -   identifier: demo_change_password
        pageRef: /demo/change/password
        parent: demo_change
        weight: 1
    -   identifier: demo_change_email
        pageRef: /demo/change/email
        parent: demo_change
        weight: 2
    -   identifier: demo_change_phone
        pageRef: /demo/change/phone
        parent: demo_change
        weight: 3
    -   identifier: demo_find_email
        pageRef: /demo/find/email
        parent: demo_find
        weight: 1
    -   identifier: demo_find_sms
        pageRef: /demo/find/sms
        parent: demo_find
        weight: 2
    -   identifier: demo_logout_normal
        pageRef: /demo/logout/normal
        parent: demo_logout
        weight: 1
knowledge_labor_union:
    -   identifier: zhgh_page
        pageRef: /tools/zhgh
        weight: 1
    -   identifier: zhgh_study
        pageRef: /tools/zhgh/study
        parent: zhgh_page
        weight: 1
    -   identifier: zhgh_passwork
        pageRef: /tools/zhgh/passwork
        parent: zhgh_page
        weight: 2
    -   identifier: zhgh_member
        pageRef: /tools/zhgh/member
        parent: zhgh_page
        weight: 3
    -   identifier: zhgh_login
        pageRef: /tools/zhgh/login
        parent: zhgh_page
        weight: 4
    -   identifier: zhgh_data
        pageRef: /tools/zhgh/data
        parent: zhgh_page
        weight: 9
    -   identifier: zhgh_log
        pageRef: /tools/zhgh/log
        parent: zhgh_page
        weight: 10
donate:
    -   identifier: donate_alipay
        weight: 1
        params:
            donate_value: "alipay"
            class:
            svg:
                useHref: "bi-alipay"
                class: "text-primary"
    -   identifier: donate_wechat
        weight: 2
        params:
            donate_value: "wechat"
            class:
            svg:
                useHref: "bi-wechat"
                class: "text-success"
theme:
    -   identifier: theme_dark
        weight: 1
        params:
            theme_value: "dark"
            class:
            svg:
                useHref: "bi-moon-stars"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: theme_light
        weight: 2
        params:
            theme_value: "light"
            class:
            svg:
                useHref: "bi-sun"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: theme_auto
        weight: 3
        params:
            theme_value: "auto"
            class:
            svg:
                useHref: "bi-circle-half"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
palette:
    -   identifier: palette_none
        weight: 1
        params:
            palette_value: "none"
            class: "text-secondary"
            svg:
                useHref: "bi-palette"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: palette_red
        weight: 10
        params:
            palette_value: "red"
            class: "text-danger"
            svg:
                useHref: "bi-droplet-half"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: palette_green
        weight: 20
        params:
            palette_value: "green"
            class: "text-success"
            svg:
                useHref: "bi-droplet-half"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: palette_blue
        weight: 30
        params:
            palette_value: "blue"
            class: "text-primary"
            svg:
                useHref: "bi-droplet-half"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
font_size:
    -   identifier: fontSize_3xs
        weight: -4
        params:
            size_value: "3xs"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_2xs
        weight: -3
        params:
            size_value: "2xs"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_xs
        weight: -2
        params:
            size_value: "xs"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_sm
        weight: -1
        params:
            size_value: "sm"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_md
        weight: 1
        params:
            size_value: "md"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_lg
        weight: 2
        params:
            size_value: "lg"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_xl
        weight: 3
        params:
            size_value: "xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_2xl
        weight: 4
        params:
            size_value: "2xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_3xl
        weight: 5
        params:
            size_value: "3xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_4xl
        weight: 6
        params:
            size_value: "4xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_5xl
        weight: 7
        params:
            size_value: "5xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_6xl
        weight: 8
        params:
            size_value: "6xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_7xl
        weight: 9
        params:
            size_value: "7xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_8xl
        weight: 10
        params:
            size_value: "8xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_9xl
        weight: 11
        params:
            size_value: "9xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
