hugoVersion:
    extended: true
    min: "0.125.3"
    max: "0.125.3"
mounts:
    -   source: site/archetypes
        target: archetypes

    -   source: site/static
        target: static/static
        excludeFiles: "{CNAME}"
    -   source: site/static/CNAME
        target: static/CNAME
    -   source: node_modules
        target: static/static/vendor
        includeFiles: "{bootstrap,bootstrap-icons,js-cookie,vanilla-cookieconsent,workbox-sw,wretch,localforage,dayjs,timeago.js,jcalendar.js,lunar-*,lozad,@docsearch,b-components-js,photoswipe,medium-zoom,qrcode,lxgw-wenkai-webfont,dragula,@uppy,uppy,disable-devtool,vditor,github-markdown-css,simple-datatables,svgedit,interactjs,sortablejs,@glidejs,clipboard,html2canvas,flag-icons,randomColor}/**"

    -   source: site/content
        target: content
        lang: zh-cn
    -   source: site/content
        target: content
        lang: en-us

    -   source: site/assets
        target: assets

    -   source: site/data
        target: data
    -   source: site/i18n
        target: i18n
    -   source: site/layouts
        target: layouts
