# default theme mode
theme:
    enable: true
    default: light
    option: [ 'light',"dark","auto" ]

# default palette color
palette:
    enable: true
    default: none
    option: [ "none","blue","green","orange","red","yellow" ]

# default font size
fontSize:
    enable: true
    default: md
    option: [ "3xs","2xs","xs","sm","md","lg","xl","2xl","3xl","4xl","5xl","6xl","7xl","8xl","9xl" ]

# default character color
color:
    text:
        enable: true
    link:
        enable: true
    code:
        enable: true

# Sidebar Type [ collapse | offcanvas ]
sidebar:
    enable: true
    post:
        enable: true
        type: offcanvas

float_tools:
    enable: true

breadcrumb:
    enable: true
    # Breadcrumb position [ top | bottom ]
    position: "top"

search:
    enable: true
    # type of search engine ["lunr", "algolia", "fuse"]
    type: "lunr"
    algolia:
        index:
        appID:
        searchKey:
    fuse:
        # https://fusejs.io/api/options.html
        isCaseSensitive: false
        minMatchCharLength: 2
        findAllMatches: false
        location: 0
        threshold: 0.3
        distance: 100
        ignoreLocation: false
        useExtendedSearch: false
        ignoreFieldNorm: false

# disable-devtool 禁用开发工具
DisableDevtool:
    enable: true

icp: "冀ICP备12018851号-7"
beian: "9999999999999999"

demo_version: "5.3"
bootstrap_version: "5.3.3"

since: "2020"

CopyleftText: "Company, Inc. All rights reserved."
CopyrightText: "Company, Inc. All rights reserved."

Github:
    root: "https://github.com/"
    organizations: ""
    username: ""
    repository: ""

Repo:
    git: "https://github.com/jzeg-net/jzeg-net.github.io"

social:
    mastodon:
        enable: true
        username: "zhangChengLin"
        host: "mastodon.social"

qrcode:
    alipay:
        donate: HTTPS://QR.ALIPAY.COM/FKX15775Y9K2OJJELTYUQ20
        account:
        group:
    weixin:
        donate: wxp://f2f0H7xW3hJst1JoX3lEdTm8ZYjfkZPKQo5XSe57dnbv11g=
        account:
        group:
    qq:
        donate: https://i.qianbao.qq.com/wallet/sqrcode.htm?m=tenpay&f=wallet&a=1&ac=CAEQguvBjgUYz9KShwY%3D_xxx_sign&u=1372616066&n=%E8%A7%A3%E6%9E%90%E7%9F%AD%E8%A7%86%E9%A2%91
        account:
        group:

analytics:
    enable: false
    googleTagManager:
        enable: true
        id:

# 下拉刷新开关
topPullDownToRefresh:
    enable: false

# 友情链接
friendLinks:
    enable: false
    page:
        enable: true
    footer:
        enable: true
    data:
        category_1:
            - "链接名称 #"
            - "链接名称 #"
        category_2:
            - "链接名称 #"
            - "链接名称 #"

# 页脚链接列表
footerLinks:
    enable: true
    group:
        # 每组分类个数没有上限，键名不允许以数字开头
        # 键名是分类名称，每一个数组格式为空格分割，具体格式是[链接文本 链接网址]
        Demo:
            - "Demo demo"
            - "账号表单演示 demo/account_form"
        links:
            - "友情链接 links"
            - "ChatGPT chatgpt"
        政策条款:
            - "隐私政策 privacy_policy"
            - "服务条款 terms_of_service"
            - "Cookie cookies"
        我们:
            - "关于 about"
            - "联系 contact"
            - "广告合作 ad"
        智慧平台:
            - "闯关 tools/zhgh/passwork"
            - "学习 tools/zhgh/study"
            - "日志 tools/zhgh/log"
