# default theme mode
theme:
    enable: true
    default: light
    option: [ 'light',"dark","auto" ]

# default palette color
palette:
    enable: true
    default: none
    option: [ "none","blue","green","orange","red","yellow" ]

# default font size
fontSize:
    enable: true
    default: md
    option: [ "3xs","2xs","xs","sm","md","lg","xl","2xl","3xl","4xl","5xl","6xl","7xl","8xl","9xl" ]

# 全站静态文件 CDN 参数
cdn:
    enable: true
    name: "jsdelivr"
    way: "npm"
    options:
        -   name: "jsdelivr"
            prefix:
                - way: "npm"
                  url: "https://cdn.jsdelivr.net/npm/"
                - way: "github"
                  url: "https://cdn.jsdelivr.net/gh/"
                - way: "wordpress"
                  url: "https://cdn.jsdelivr.net/wp/"
                - way: "es"
                  url: "https://esm.run/"

# default font family
font_family:
    enable: true
    cdn:
        enable: true
    name: "lxgw-wenkai-webfont"
    options:
        -   name: "lxgw-wenkai-webfont"
        -   name: "lxgw-wenkai-tc-webfont"
        -   name: "lxgw-wenkai-lite-webfont"
        -   name: "lxgw-wenkai-screen-webfont"

# default character color
color:
    text:
        enable: true
    link:
        enable: true
    code:
        enable: true

# Sidebar Type [ collapse | offcanvas ]
sidebar:
    enable: true
    post:
        enable: true
        type: offcanvas

float_tools:
    enable: true

breadcrumb:
    enable: true
    # Breadcrumb position [ top | bottom ]
    position: "top"

search:
    enable: true
    # type of search engine ["lunr", "algolia", "fuse"]
    type: "lunr"
    algolia:
        index:
        appID:
        searchKey:
    fuse:
        # https://fusejs.io/api/options.html
        isCaseSensitive: false
        minMatchCharLength: 2
        findAllMatches: false
        location: 0
        threshold: 0.3
        distance: 100
        ignoreLocation: false
        useExtendedSearch: false
        ignoreFieldNorm: false

# disable-devtool 禁用开发工具
DisableDevtool:
    enable: true

since: "2020"

Github:
    root: "https://github.com/"
    organizations: ""
    username: ""
    repository: ""

Repo:
    git: "https://github.com/jzeg-net/jzeg-net.github.io"

analytics:
    umami:
        enable: true
        share:
            enable: true
    googleTagManager:
        enable: false

# 下拉刷新开关
topPullDownToRefresh:
    enable: false

# 友情链接
friendLinks:
    page:
        enable: true
    footer:
        enable: true

# 订阅通讯
newsletter:
    footer:
        enable: true

# 页脚链接列表
footerLinks:
    enable: true
