main:
    -   identifier: menu_home
        name: "Home"
        pageRef: /
        weight: 1
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_posts
        name: "Posts"
        pageRef: /posts
        weight: 2
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_gallery
        name: "Gallery"
        pageRef: /gallery
        weight: 3
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_video
        name: "Video"
        pageRef: /video
        weight: 3
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_more
        name: "More"
        pageRef:
        weight: 7
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_contact
        name: "Contact"
        pageRef: /contact
        parent: menu_more
        weight: 1
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_about
        name: "About"
        pageRef: /about
        parent: menu_more
        weight: 2
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_ad
        name: "AD"
        pageRef: /ad
        parent: menu_more
        weight: 3
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_chatgpt
        name: "Chat GPT"
        pageRef: /chatgpt
        parent: menu_more
        weight: 4
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_tools
        name: "Toolbox"
        pageRef: /tools
        parent: menu_more
        weight: 5
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_record
        name: "Daily Check In"
        pageRef: /sign_record
        parent: menu_more
        weight: 6
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_calendar
        name: "Calendar"
        pageRef: /calendar
        parent: menu_more
        weight: 6
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_cookies
        name: "Cookie Policy"
        pageRef: /cookies
        parent: menu_more
        weight: 6
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_links
        name: "Links"
        pageRef: /links
        parent: menu_more
        weight: 6
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_edit
        name: "Edit"
        pageRef: /edit
        parent: menu_more
        weight: 8
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: menu_shop
        name: "Shop"
        pageRef: /shop
        parent: menu_more
        weight: 7
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
demo:
    -   identifier: menu_demo
        name: "Demo"
        pageRef: /demo
        weight: 1
        params:
            class:
            svg:
                useHref:
                class:
                size: [ width: 16, height: 16 ]
    -   identifier: demo_login
        name: "LogIn"
        pageRef: /demo/login
        parent: menu_demo
        weight: 1
    -   identifier: demo_signup
        name: "SignUp"
        pageRef: /demo/signup
        parent: menu_demo
        weight: 2
    -   identifier: demo_reset
        name: "Reset"
        pageRef: /demo/reset
        parent: menu_demo
        weight: 3
    -   identifier: demo_change
        name: "Change"
        pageRef: /demo/change
        parent: menu_demo
        weight: 4
    -   identifier: demo_find
        name: "Find"
        pageRef: /demo/find
        parent: menu_demo
        weight: 5
    -   identifier: demo_logout
        name: "Quit"
        pageRef: /demo/logout
        parent: menu_demo
        weight: 6
    -   identifier: demo_login_normal
        name: "Normal LogIn"
        pageRef: /demo/login/normal
        parent: demo_login
        weight: 1
    -   identifier: demo_login_email
        name: "Email LogIn"
        pageRef: /demo/login/email
        parent: demo_login
        weight: 2
    -   identifier: demo_login_sms
        name: "SMS LogIn"
        pageRef: /demo/login/sms
        parent: demo_login
        weight: 3
    -   identifier: demo_signup_normal
        name: "Normal SignUp"
        pageRef: /demo/signup/normal
        parent: demo_signup
        weight: 1
    -   identifier: demo_signup_email
        name: "Email SignUp"
        pageRef: /demo/signup/email
        parent: demo_signup
        weight: 2
    -   identifier: demo_signup_sms
        name: "SMS SignUp"
        pageRef: /demo/signup/sms
        parent: demo_signup
        weight: 3
    -   identifier: demo_reset_email
        name: "Reset Via Email"
        pageRef: /demo/reset/email
        parent: demo_reset
        weight: 1
    -   identifier: demo_reset_sms
        name: "Reset Via SMS"
        pageRef: /demo/reset/sms
        parent: demo_reset
        weight: 2
    -   identifier: demo_change_password
        name: "Change Password"
        pageRef: /demo/change/password
        parent: demo_change
        weight: 1
    -   identifier: demo_change_email
        name: "Change Email"
        pageRef: /demo/change/email
        parent: demo_change
        weight: 2
    -   identifier: demo_change_phone
        name: "Change Phone Number"
        pageRef: /demo/change/phone
        parent: demo_change
        weight: 3
    -   identifier: demo_find_email
        name: "Find Via Email"
        pageRef: /demo/find/email
        parent: demo_find
        weight: 1
    -   identifier: demo_find_sms
        name: "Find Via SMS"
        pageRef: /demo/find/sms
        parent: demo_find
        weight: 2
    -   identifier: demo_logout_normal
        name: "Normal Exit"
        pageRef: /demo/logout/normal
        parent: demo_logout
        weight: 1
knowledge_labor_union:
    -   identifier: zhgh_page
        name: "Wisdom"
        pageRef: /tools/zhgh
        weight: 1
    -   identifier: zhgh_study
        name: "Study"
        pageRef: /tools/zhgh/study
        parent: zhgh_page
        weight: 1
    -   identifier: zhgh_passwork
        name: "Passwork"
        pageRef: /tools/zhgh/passwork
        parent: zhgh_page
        weight: 2
    -   identifier: zhgh_member
        name: "Member"
        pageRef: /tools/zhgh/member
        parent: zhgh_page
        weight: 3
    -   identifier: zhgh_login
        name: "Login"
        pageRef: /tools/zhgh/login
        parent: zhgh_page
        weight: 4
    -   identifier: zhgh_data
        name: "Data"
        pageRef: /tools/zhgh/data
        parent: zhgh_page
        weight: 9
    -   identifier: zhgh_log
        name: "Log"
        pageRef: /tools/zhgh/log
        parent: zhgh_page
        weight: 10
donate:
    -   identifier: donate
        name: "Donate"
    -   identifier: donate_alipay
        name: "Donate Via Alipay"
        parent: donate
        weight: 1
        params:
            donate_value: "alipay"
            class:
            svg:
                useHref: "bi-alipay"
                class: "text-primary"
    -   identifier: donate_wechat
        name: "Donate Via Wechat"
        parent: donate
        weight: 2
        params:
            donate_value: "wechat"
            class:
            svg:
                useHref: "bi-wechat"
                class: "text-success"
language:
    -   identifier: language
        name: Language
        params:
            toggle_text: "Language Switch"
color:
    -   identifier: color
        name: Character Color
        params:
            toggle_text: "Character Color Switch"
theme:
    -   identifier: theme
        name: Theme
        params:
            toggle_text: "Theme Switch"
    -   identifier: theme_dark
        name: "Dark"
        parent: theme
        weight: 1
        params:
            theme_value: "dark"
            class:
            svg:
                useHref: "bi-moon-stars"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: theme_light
        name: "Light"
        parent: theme
        weight: 2
        params:
            theme_value: "light"
            class:
            svg:
                useHref: "bi-sun"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: theme_auto
        name: "Auto"
        parent: theme
        weight: 3
        params:
            theme_value: "auto"
            class:
            svg:
                useHref: "bi-circle-half"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
palette:
    -   identifier: palette
        name: "Palette"
        params:
            toggle_text: "Hue Switch"
    -   identifier: palette_none
        name: "Default"
        parent: palette
        weight: 1
        params:
            palette_value: "none"
            class: "text-secondary"
            svg:
                useHref: "bi-palette"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: palette_red
        name: "Red"
        parent: palette
        weight: 10
        params:
            palette_value: "red"
            class: "text-danger"
            svg:
                useHref: "bi-droplet-half"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: palette_green
        name: "Green"
        parent: palette
        weight: 20
        params:
            palette_value: "green"
            class: "text-success"
            svg:
                useHref: "bi-droplet-half"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: palette_blue
        name: "Blue"
        parent: palette
        weight: 30
        params:
            palette_value: "blue"
            class: "text-primary"
            svg:
                useHref: "bi-droplet-half"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
font_size:
    -   identifier: font
        name: "Font"
        params:
            toggle_text: "Font Size Switch"
    -   identifier: fontSize_3xs
        name: "3xs"
        parent: font
        weight: -4
        params:
            size_value: "3xs"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_2xs
        name: "2xs"
        parent: font
        weight: -3
        params:
            size_value: "2xs"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_xs
        name: "xs"
        parent: font
        weight: -2
        params:
            size_value: "xs"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_sm
        name: "sm"
        parent: font
        weight: -1
        params:
            size_value: "sm"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_md
        name: "md"
        parent: font
        weight: 1
        params:
            size_value: "md"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_lg
        name: "lg"
        parent: font
        weight: 2
        params:
            size_value: "lg"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_xl
        name: "xl"
        parent: font
        weight: 3
        params:
            size_value: "xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_2xl
        name: "2xl"
        parent: font
        weight: 4
        params:
            size_value: "2xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_3xl
        name: "3xl"
        parent: font
        weight: 5
        params:
            size_value: "3xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_4xl
        name: "4xl"
        parent: font
        weight: 6
        params:
            size_value: "4xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_5xl
        name: "5xl"
        parent: font
        weight: 7
        params:
            size_value: "5xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_6xl
        name: "6xl"
        parent: font
        weight: 8
        params:
            size_value: "6xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_7xl
        name: "7xl"
        parent: font
        weight: 9
        params:
            size_value: "7xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_8xl
        name: "8xl"
        parent: font
        weight: 10
        params:
            size_value: "8xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
    -   identifier: fontSize_9xl
        name: "9xl"
        parent: font
        weight: 11
        params:
            size_value: "9xl"
            class:
            svg:
                useHref: "bi-fonts"
                class: "bi me-2"
                size: [ width: 16, height: 16 ]
