# baseURL: ""
locale: "zh-CN"
label: "简体中文(中国)"
direction: "ltr"
timeZone: "Asia/Shanghai"
title: "杰格网"
weight: 1
hasCJKLanguage: true
params:
    CountryCode: cn
    Subtitle: "子标题"
    Description: "默认描述"
    header_separator: " - "
