# baseURL: ""
languageName: "English (United States)"
languageDirection: "ltr"
languageCode: "en-US"
timeZone: "America/New_York"
title: "JieGe"
weight: 21
hasCJKLanguage: false
params:
    CountryCode: us
    Subtitle: "Subtitle"
    Description: "Default Description"
    header_separator: " - "
