# baseURL: ""
locale: "en-US"
label: "English (United States)"
direction: "ltr"
timeZone: "America/New_York"
title: "JieGe"
weight: 21
hasCJKLanguage: false
params:
    CountryCode: us
    Subtitle: "Subtitle"
    Description: "Default Description"
    header_separator: " - "
